apiVersion: v1
kind: Secret
metadata:
  name: openai-api-secret
type: Opaque
data:
  OPENAI_API_KEY: RHFwcGpTMHg4YlBLdlVzZ3JIcTRjNGpsMWlTemVkMFNqRGdoTkJrbnJYT3F6dU82UmltMEpRUUk5OUJEQUNmaE1rNVhKM3czQUFBQkFDT0cwRXBa
# Note: The value of OPENAI_API_KEY must be Base64-encoded.
# You can encode it using the following command:
# echo -n "your-actual-api-key" | base64

